/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.teddys.network;

import edu.teddys.objects.box.items.Item;
import edu.teddys.objects.Jetpack;
import edu.teddys.objects.weapons.Weapon;
import java.awt.Point;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 *
 * @author cm
 */
public class Client implements EncryptionAvailableInterface, NetworkCommunicatorAPI {
  
  /**
   * Autogenerated on demand.
   */
  private Integer id;
  /**
   * Team allocation if available.
   */
  private Team team;
  /**
   * The current Health Points ranging from 0 to 100.
   */
  private Integer health = 100;
  /**
   * Server ip the client uses for the gameplay.
   */
  private String serverIP;
  /**
   * Public key of the server for the encryption.
   */
  private String pubKeyServer;
  /**
   * Indicates whether a server connection is active.
   */
  private boolean currentConnection = false;
  /**
   * Information when the client has connected to the server.
   */
  private Date joinedServer;
  /**
   * Displayed name.
   */
  private String name;
  /**
   * Position in the current map. 
   */
  private Point position = new Point();
//  private Map map;
  private Jetpack jetpack = new Jetpack();
  /**
   * The client can only handle one item which is bound to the user, so save it here.
   */
  private Item currentItem;
  /**
   * The list of achieved weapons. Initially, there's always the simple gun available.
   */
  private List<Weapon> weapons = new ArrayList<Weapon>();
  /**
   * Index in the weapon list for the current weapon.
   */
  private Integer currentWeapon;
  /**
   * The last 10 pings to the server. This is used for statistical and game-dependent
   * issues. For example, the server balancing or anti-lagging.
   */
  private List<Integer> lastPings = new ArrayList<Integer>();
  /**
   * Session-related information, that is the number of deaths, kills, rounds etc.
   */
  private SessionClientData session;
  
  private NetworkCommunicatorSpidermonkeyClient networkCommunicator = new NetworkCommunicatorSpidermonkeyClient();

  public String getPubKey(String pubKeyClient) {
    return networkCommunicator.getPubKey(pubKeyClient);
  }

  public void notifyClients(NetworkMessage message) {
    throw new UnsupportedOperationException("Not supported yet.");
  }

  public NetworkMessage join(Client client) {
    throw new UnsupportedOperationException("Not supported yet.");
  }

  public NetworkMessage disconnect(Client client) {
    throw new UnsupportedOperationException("Not supported yet.");
  }

  public void sendChecksum(String checkSumFiles) {
    throw new UnsupportedOperationException("Not supported yet.");
  }

  public void fireWeapon(Client client, Weapon weapon) {
    throw new UnsupportedOperationException("Not supported yet.");
  }

  public void activateItem(Client client, Item item) {
    throw new UnsupportedOperationException("Not supported yet.");
  }

  public boolean isCurrentConnection() {
    return currentConnection;
  }

  public void setCurrentConnection(boolean currentConnection) {
    this.currentConnection = currentConnection;
  }

  public Item getCurrentItem() {
    return currentItem;
  }

  public void setCurrentItem(Item currentItem) {
    this.currentItem = currentItem;
  }

  public Integer getCurrentWeapon() {
    return currentWeapon;
  }

  public void setCurrentWeapon(Integer currentWeapon) {
    this.currentWeapon = currentWeapon;
  }

  public Integer getHealth() {
    return health;
  }

  public void setHealth(Integer health) {
    this.health = health;
  }

  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Jetpack getJetpack() {
    return jetpack;
  }

  public void setJetpack(Jetpack jetpack) {
    this.jetpack = jetpack;
  }

  public Date getJoinedServer() {
    return joinedServer;
  }

  public void setJoinedServer(Date joinedServer) {
    this.joinedServer = joinedServer;
  }

  public List<Integer> getLastPings() {
    return lastPings;
  }

  public void setLastPings(List<Integer> lastPings) {
    this.lastPings = lastPings;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Point getPosition() {
    return position;
  }

  public void setPosition(Point position) {
    this.position = position;
  }

  public String getPubKeyServer() {
    return pubKeyServer;
  }

  public void setPubKeyServer(String pubKeyServer) {
    this.pubKeyServer = pubKeyServer;
  }

  public String getServerIP() {
    return serverIP;
  }

  public void setServerIP(String serverIP) {
    this.serverIP = serverIP;
  }

  public SessionClientData getSession() {
    return session;
  }

  public void setSession(SessionClientData session) {
    this.session = session;
  }

  public Team getTeam() {
    return team;
  }

  public void setTeam(Team team) {
    this.team = team;
  }

  public List<Weapon> getWeapons() {
    return weapons;
  }

  public void setWeapons(List<Weapon> weapons) {
    this.weapons = weapons;
  }
  
  
}
