/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.teddys.network;

import edu.teddys.objects.Jetpack;
import java.awt.Point;

/**
 *
 * @author cm
 */
public class ClientData {
  /**
   * Autogenerated on connection with a server.
   */
  private Integer id;
  /**
   * The current Health Points ranging from 0 to 100.
   */
  private Integer health = 100;
  /**
   * Displayed name.
   */
  private String name = "Player";
  /**
   * Position in the current map. 
   */
  private Point position = new Point();
  private Jetpack jetpack = new Jetpack();
  /**
   * Session-related information, that is the number of deaths, kills, rounds etc.
   */
  private SessionClientData session;
  /**
   * Team allocation if available.
   */
  private Integer team;

  public Integer getHealth() {
    return health;
  }

  public void setHealth(Integer health) {
    this.health = health;
  }

  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Jetpack getJetpack() {
    return jetpack;
  }

  public void setJetpack(Jetpack jetpack) {
    this.jetpack = jetpack;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Point getPosition() {
    return position;
  }

  public void setPosition(Point position) {
    this.position = position;
  }

  public SessionClientData getSession() {
    return session;
  }

  public void setSession(SessionClientData session) {
    this.session = session;
  }

  public Integer getTeamID() {
    return team;
  }

  public void setTeam(Integer team) {
    this.team = team;
  }
  
}
