/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.teddys.network;

import edu.teddys.GameMode;
import edu.teddys.objects.box.items.Item;
import edu.teddys.objects.weapons.Weapon;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 *
 * @author cm
 */
public class Server implements EncryptionAvailableInterface, NetworkCommunicatorAPI {
  
  /**
   * Autogenerated on demand.
   */
  private String id;
  private Date created;
  private String name;
//  private Map map;
  private List<Team> teams = new ArrayList<Team>();
  private GameMode gameMode;
  private boolean isDiscoverable = false;

  public String getPubKey(String pubKeyClient) {
    throw new UnsupportedOperationException("Not supported yet.");
  }

  public void notifyClients(NetworkMessage message) {
    throw new UnsupportedOperationException("Not supported yet.");
  }

  public NetworkMessage join(Client client) {
    throw new UnsupportedOperationException("Not supported yet.");
  }

  public NetworkMessage disconnect(Client client) {
    throw new UnsupportedOperationException("Not supported yet.");
  }

  public void sendChecksum(String checkSumFiles) {
    throw new UnsupportedOperationException("Not supported yet.");
  }

  public void fireWeapon(Client client, Weapon weapon) {
    throw new UnsupportedOperationException("Not supported yet.");
  }

  public void activateItem(Client client, Item item) {
    throw new UnsupportedOperationException("Not supported yet.");
  }
  
  
}
