/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.teddys.network;

import edu.teddys.GameMode;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 *
 * @author cm
 */
public class Server implements EncryptionAvailableInterface {
  
  /**
   * Autogenerated on demand.
   */
  private String id;
  private Date created;
  private String name;
//  private Map map;
  private List<Team> teams = new ArrayList<Team>();
  private GameMode gameMode;
  private boolean isDiscoverable = false;
  
}
