/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.teddys.network;

import edu.teddys.GameMode;
import edu.teddys.network.messages.NetworkMessage;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 *
 * @author cm
 */
public class TeddyServer implements EncryptionAvailableInterface, NetworkCommunicatorAPI {
  
  /**
   * Autogenerated on demand.
   */
  private String id;
  private Date created;
  private String name;
//  private Map map;
  private List<Team> teams = new ArrayList<Team>();
  private GameMode gameMode;
  private boolean isDiscoverable = false;
  
  private static TeddyServer instance;
  
  public static TeddyServer getInstance() {
    if(instance == null) {
      instance = new TeddyServer();
    }
    return instance;
  }
  
  public void startServer() {
    NetworkCommunicatorSpidermonkeyServer.getInstance().startServer();
  }
  
  public void stopServer() {
    NetworkCommunicatorSpidermonkeyServer.getInstance().shutdownServer();
  }
  
  public String getPubKey(String pubKeyClient) {
    return NetworkCommunicatorSpidermonkeyServer.getInstance().getPubKey(pubKeyClient);
  }

  public void send(NetworkMessage message) {
    NetworkCommunicatorSpidermonkeyServer.getInstance().send(message);
  }

  public boolean join() {
    return NetworkCommunicatorSpidermonkeyServer.getInstance().join();
  }

  public void disconnect(TeddyClient client) {
    NetworkCommunicatorSpidermonkeyServer.getInstance().disconnect(client);
  }  
  
}
