/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.teddys.network;

import com.jme3.network.ConnectionListener;
import com.jme3.network.HostedConnection;
import com.jme3.network.Server;
import edu.teddys.network.messages.NetworkMessage;
import edu.teddys.network.messages.NetworkMessageInfo;
import edu.teddys.network.messages.server.ReqMessageSendClientData;
import java.util.Date;

/**
 *
 * @author cm
 */
public class TeddyServer implements NetworkCommunicatorAPI, ConnectionListener {
  
  /**
   * Autogenerated on demand.
   */
  private TeddyServerData data;
  
  private static TeddyServer instance;
  
  public static TeddyServer getInstance() {
    if(instance == null) {
      instance = new TeddyServer();
    }
    return instance;
  }
  
  public void startServer() {
    NetworkCommunicatorSpidermonkeyServer.getInstance().startServer(this);
    data = new TeddyServerData();
    data.setCreated(new Date());
    //TODO check
    data.setDiscoverable(true);
    //TODO check
    data.setName("Todesangst");
    //TODO set game mode
  }
  
  public void stopServer() {
    NetworkCommunicatorSpidermonkeyServer.getInstance().shutdownServer();
    // reset data
    data = null;
  }
  
  public String getPubKey(String pubKeyClient) {
    return NetworkCommunicatorSpidermonkeyServer.getInstance().getPubKey(pubKeyClient);
  }

  public void send(NetworkMessage message) {
    NetworkCommunicatorSpidermonkeyServer.getInstance().send(message);
  }

  public boolean join() {
    // dummy value
    return false;
  }

  public void disconnect(TeddyClient client) {
  }

  protected TeddyServerData getData() {
    return data;
  }

  public void setData(TeddyServerData data) {
    this.data = data;
  }
  
  /**
   * Adds client data to the current list. Existing data will be overwritten!
   */
  public void setClientData(Integer clientID, TeddyClient client) {
    getData().getClients().put(clientID, client);
  }

  public void connectionAdded(Server server, HostedConnection conn) {
    getData().getConnections().add(conn);
    String message = String.format(
            "New connection (%s) arrived!",
            conn.getAddress());
    NetworkMessageInfo info = new NetworkMessageInfo(message);
    send(info);
    System.out.println(message);
    ReqMessageSendClientData sendMsg = new ReqMessageSendClientData();
    conn.send(sendMsg);
  }

  public void connectionRemoved(Server server, HostedConnection conn) {
    if(getData().getConnections().contains(conn)) {
      
      //TODO search for the client data of the HostedConnection and remove it 
      // from list
      
      String message = String.format(
              "Client %s committed suicide.",
              conn.getId());
      getData().getConnections().remove(conn);
      NetworkMessageInfo info = new NetworkMessageInfo(message);
      send(info);
      System.out.println(message);
      return;
    }
    System.err.println(
        String.format("Connection remove request failed from IP %s!",
        conn.getAddress()));
  }
  
}
